config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'

  get 'order_lines/index'

  get 'order_lines/new'

  devise_scope :admin do
    get 'admins/sign_in', to: 'publics#index' #failed sign ins will redirect to main page
    authenticated :admin do
      resources :cashiers
      resources :products
      resources :report
      root 'products#index', as: :authenticated_admin_root
      get 'report/index'
    end
  end
  
  devise_scope :cashier do
    get 'cashiers/sign_in', to: 'publics#index' #failed sign ins will redirect to main page
    # added below
    authenticated :cashier do
      resources :products
      resources :orders
      resources :order_lines
      root 'orders#index'
    end
  end

  devise_for :cashiers
  devise_for :admins
  root 'publics#index'
  get 'publics/catalogue'
  get 'order_lines/index'
  get 'order_lines/new'
  get 'orders/new'
  get 'orders/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :cashiers
end

# removed :registerable

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :admin
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_lines, inverse_of: 'order'
  accepts_nested_attributes_for :order_lines, reject_if: :all_blank, allow_destroy: true
  belongs_to :cashier
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  has_and_belongs_to_many :products
  belongs_to :order
  
end

app/models/product.rb
class Product  < ActiveRecord::Base
    has_many :order_lines
    has_many :orders, :through => :order_lines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  before_action :set_cashier, only: [:edit, :show, :update, :destroy
  ]
  
  def index
    @cashiers = Cashier.all
  end

  def new
    @cashier = current_admin.cashiers.new
  end
  
  def create
   @cashier = current_admin.cashiers.new(cashier_params)
   
    @cashier.status = true
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully added."
    else
      render :new
     
    end
  end
  
  def edit
  end

  def show
  end
 
  def destroy
    @cashier = Cashier.find(params[:id])
    if @cashier.status == true
      @cashier.status = false
    else
      @cashier.status = true
    end
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    end
  end
  
  #version below turns change status to "delete cashier"
  # def destroy
  #   @cashier = Cashier.find(params[:id])
  #   @cashier.destroy
    
  #   redirect_to cashiers_path
  # end
    
  def update
    @cashier = Cashier.find(params[:id])
    @cashier.destroy
    @cashier = current_admin.cashiers.new(cashier_params)
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    else
      render :edit
    end
  end
  
  private
    def set_cashier
      @cashier = Cashier.find_by(id: params[:id])
      redirect_to cashiers_path, notice: "Cashier not found." if @cashier.nil?
    end
    
    def cashier_params
       params.require(:cashier).permit(:email, :password, :password_confirmation, :name) #-> Tried this
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:edit, :show, :update, :destroy]
  
  def index
      @orders = Order.all
      @order_lines = OrderLine.all
  end
  
  def new
      @order = Order.new
  end
  
  def create
      @order = Order.new(order_params)
      @order.cashier = current_cashier
      @order.total_price = 0
      
      if @order.save
        
        redirect_to orders_path, notice: "Order successfully placed."
      else
        render :new
      end
  end
  
  def destroy
    # what?
      @order = Order.find(params[:id])
      @order.destroy
    
      redirect_to orders_path
  end
  
  def back
      redirect_to :back
  end
  
  private
    def set_order
        @order = Order.find_by(id: params[:id])
        redirect_to orders_path, notice: "Order not found." if @order.nil?
    end
    
    def order_params
      params.require(:order).permit(:cashier_id, :total_cash, :cash, order_line_attributes: [:id, :product_id, :order_id, :quantity, :price, :_destroy])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :show, :update, :destroy]
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    @product.status = "Active"
    
    if @product.save
      redirect_to products_path, notice: "Product successfully added."
    else
      render :new
    end
  end
  
  def edit
    
  end

  def show
  end
  
  def update
    @product.update(product_params)
    if @product.save
      redirect_to products_path, notice: "Product successfully updated."
    else
      render :edit
    end
  end
  
  def destroy
    if @product.status == true
      @product.status = false
    else
      @product.status = true
    end
    
    if @product.save
      redirect_to products_path, notice: "Product successfully updated."
    end
  end
  
  private
    def set_product
      @product = Product.find_by(id: params[:id])
      redirect_to products_path, notice: "Product not found." if @product.nil?
    end
    
    def product_params
      params.require(:product).permit!
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  end
  
  def catalogue
    @products = Product.all
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  
  def index
     @products = Product.all
     
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def index
    @order_line = OrderLine.all
    @orders = Order.all
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_controller_helper.rb
module OrdersControllerHelper
    @order = Order.new 
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/publics/catalogue.html.erb
<h1>Products</h1>

<table class="table table-striped" style="background-color: Khaki ">
    <thead>
        <th>Name</th>
        <th>Price</th>
        <th>Status</th>
    </thead>
    <tbody>
        <% @products.each do |product| %>
            <tr>
                <td class="col-md-10">
                    <%= product.name %>
                </td>
                <td class="col-md-1">
                    <%= product.price %>
                </td>
                <td class="col-md-1">
                    <% if product.status == true %>
                    <p class= "bg-success">Active</p>
                    <% else %>
                    <p class= "bg-danger">Inactive </p>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/publics/index.html.erb
  <div class="row">
    <div class="col-md-12">
      <h1>Welcome!</h1>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-6">
    <h2>Sign in as Admin</h2>
    <%= simple_form_for(:admin, :url => session_path(:admin), :class => 'form-vertical') do |f| %>
      <%= f.input :email, placeholder: 'Admin email', required: false %>
      <%= f.input :password, placeholder: 'Password', required: false %>
      <%= f.input :remember_me, as: :boolean %>
      <%= f.submit 'Sign in', class: "btn btn-primary" %>
      <p>
      <%= link_to "Forgot your password?", new_password_path(:admin) %>
      </p>
    <% end %>
    </div>
    <div class="col-md-6">
    <h2>Sign in as Cashier</h2>
    <%= simple_form_for(:cashier, :url => session_path(:cashier), :class => 'form-vertical') do |f| %>
      <%= f.input :email, placeholder: 'Cashier email', required: false %>
      <%= f.input :password, placeholder: 'Password', required: false %>
      <%= f.input :remember_me, as: :boolean %>
      <%= f.submit 'Sign in', class: "btn btn-primary" %>
      <p>
      <%= link_to "Forgot your password?", new_password_path(:cashier) %>
      </p>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "View public catalogue", publics_catalogue_path, class: "btn btn-primary btn-lg btn-block" %>
    </div>
  </div>

app/views/report/index.html.erb
<h1>Daily Saleseport</h1>
<h5><small><i>
    As of <%= Time.now.strftime("%Y-%m-%d") %>
    </i></small></h5>

<table class = "table table-striped">
    <thead>
        <th>Product</th>
        <th>Qunatity sold today</th>
    </thead>
    <tbody>
        <% @products.each do |product| %>
        <tr>
            <td class="col-md-6">
            <%= product.name %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/summary/index.html.erb
<h1>Order Summary</h1>
<%= simple_form_for @order do |f| %>
<table class = "table table-striped">
    <thead>
        <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
        <th>Cash</th>
        </tr>
    </thead>
    <tbody>
        
        <% @orders.each do |order| %>
        <tr>
        <td><%= order.order_lines.name %> </td>
        <td><%= order.order_lines %> </td>
        <% end %>
        <% @orders.each do |order| %>
        <td> <%= order.total_price %></td>
        <td><%= order.cash %></td>
        </tr>
        <% end %>
    </tbody>
    Input payment here:
    <%= f.input:cash, as: "decimal", placeholder: "Payment", input_html: { min: '0', step: 'any' }, required: true %>
    <%= f.submit_tag 'Confirm', class: "btn btn-primary" %>    
</table>
<% end %>