config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'

  get 'order_lines/index'

  get 'order_lines/new'

  devise_scope :admin do
    get 'admins/sign_in', to: 'publics#index' #failed sign ins will redirect to main page
    authenticated :admin do
      resources :cashiers
      resources :products
      resources :report
      root 'products#index', as: :authenticated_admin_root
      get 'report/index'
    end
  end
  
  devise_scope :cashier do
    get 'cashiers/sign_in', to: 'publics#index' #failed sign ins will redirect to main page
    # added below
    authenticated :cashier do
      resources :products
      resources :orders
      resources :order_lines
      root 'orders#index'
    end
  end

  devise_for :cashiers
  devise_for :admins
  root 'publics#index'
  get 'publics/catalogue'
  get 'order_lines/index'
  get 'order_lines/new'
  get 'orders/new'
  get 'orders/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :cashiers
end

# removed :registerable

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :admin
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_lines, inverse_of: 'order'
  accepts_nested_attributes_for :order_lines, reject_if: :all_blank, allow_destroy: true
  belongs_to :cashier
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  has_and_belongs_to_many :products
  belongs_to :order
  
end

app/models/product.rb
class Product  < ActiveRecord::Base
    has_many :order_lines
    has_many :orders, :through => :order_lines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  before_action :set_cashier, only: [:edit, :show, :update, :destroy
  ]
  
  def index
    @cashiers = Cashier.all
  end

  def new
    @cashier = current_admin.cashiers.new
  end
  
  def create
   @cashier = current_admin.cashiers.new(cashier_params)
   
    @cashier.status = true
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully added."
    else
      render :new
     
    end
  end
  
  def edit
  end

  def show
  end
 
  def destroy
    @cashier = Cashier.find(params[:id])
    if @cashier.status == true
      @cashier.status = false
    else
      @cashier.status = true
    end
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    end
  end
  
  #version below turns change status to "delete cashier"
  # def destroy
  #   @cashier = Cashier.find(params[:id])
  #   @cashier.destroy
    
  #   redirect_to cashiers_path
  # end
    
  def update
    @cashier = Cashier.find(params[:id])
    @cashier.destroy
    @cashier = current_admin.cashiers.new(cashier_params)
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    else
      render :edit
    end
  end
  
  private
    def set_cashier
      @cashier = Cashier.find_by(id: params[:id])
      redirect_to cashiers_path, notice: "Cashier not found." if @cashier.nil?
    end
    
    def cashier_params
       params.require(:cashier).permit(:email, :password, :password_confirmation, :name) #-> Tried this
    end
    
end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  # before_action :set_order_line, only: [:edit, :show, :update, :destroy]
  #:inverse_of => :OrderLine
  
  # I don't think there is an index page for order lines.
  # def index
  #   @order_lines = OrderLine.all
  # end
  
  def new
    @order_line = OrderLine.new
    @order_line.order = current_order
  end
  
  def create
    @order_line = OrderLine.new(order_line_params)
    
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:edit, :show, :update, :destroy]
  
  def index
      @orders = Order.all
      @order_lines = OrderLine.all
  end
  
  def new
      @order = Order.new
  end
  
  def create
      @order = Order.new(order_params)
      @order.cashier = current_cashier
      @order.total_price = 0
      
      if @order.save
        
        redirect_to orders_path, notice: "Order successfully placed."
      else
        render :new
      end
  end
  
  def destroy
    # what?
      @order = Order.find(params[:id])
      @order.destroy
    
      redirect_to orders_path
  end
  
  def back
      redirect_to :back
  end
  
  private
    def set_order
        @order = Order.find_by(id: params[:id])
        redirect_to orders_path, notice: "Order not found." if @order.nil?
    end
    
    def order_params
      params.require(:order).permit(:cashier_id, :total_cash, :cash, order_line_attributes: [:id, :product_id, :order_id, :quantity, :price, :_destroy])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :show, :update, :destroy]
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    @product.status = "Active"
    
    if @product.save
      redirect_to products_path, notice: "Product successfully added."
    else
      render :new
    end
  end
  
  def edit
    
  end

  def show
  end
  
  def update
    @product.update(product_params)
    if @product.save
      redirect_to products_path, notice: "Product successfully updated."
    else
      render :edit
    end
  end
  
  def destroy
    if @product.status == true
      @product.status = false
    else
      @product.status = true
    end
    
    if @product.save
      redirect_to products_path, notice: "Product successfully updated."
    end
  end
  
  private
    def set_product
      @product = Product.find_by(id: params[:id])
      redirect_to products_path, notice: "Product not found." if @product.nil?
    end
    
    def product_params
      params.require(:product).permit!
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  end
  
  def catalogue
    @products = Product.all
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  
  def index
     @products = Product.all
     
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def index
    @order_line = OrderLine.all
    @orders = Order.all
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_controller_helper.rb
module OrdersControllerHelper
    @order = Order.new 
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/cashiers/edit.html.erb
<h1>Edit Cashier</h1>

<%= simple_form_for @cashier do |f| %>

    <%= f.input :email, placeholder: "Cashier email", required: true %>
    <%= f.input :password, placeholder: "Cashier password", required: true %>
    <%= f.input :password_confirmation, placeholder: "Cashier password", required: true %>
    <%= f.input :name, placeholder: "Cashier name", required: true %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to "Go back to Cashiers list", cashiers_path, class: "btn btn-primary" %>

<% end %>

app/views/cashiers/index.html.erb
<h1>Cashiers</h1>
<%= link_to "Add Cashier", new_cashier_path, class: "btn btn-primary" %>


<table class="table table-striped" style="background-color: Khaki ">
    <thead>
        <th>Name</th>
        <th>Email</th>
        <th>Created By</th>
        <th>Status</th>
        <th colspan="3"></th>
    </thead>
    <tbody>
        <% @cashiers.each do |cashier| %>
            <tr>
                <td>
                    <%= cashier.name %>
                </td>
                <td>
                    <%= cashier.email %>
                </td>
                <td>
                    <%= cashier.admin.email %>
                </td>
                <td>
                    <%#= cashier.status ? "Active" : "Inactive" %>
                      <% if cashier.status == true %>
                    <p class= "label label-success">Active</p>
                    <% else %>
                    <p class= "label label-danger">Inactive </p>
                    <% end %>
                </td>
                <td>
                    <%= link_to "Edit", edit_cashier_path(cashier), class: "btn btn-primary" %>
                </td>
                <td>
                    <%= link_to "View", cashier, class: "btn btn-warning" %>
                </td>
                <td>
                    <%#= link_to "Change status", cashier, method: :delete, class: "btn btn-primary" %>
                     <% if cashier.status == true %>
                    <%= link_to "Deactivate", cashier, method: :delete, class: "btn btn-danger" %>
                    <% else %>
                    <%= link_to "Activate", cashier, method: :delete, class: "btn btn-success" %>
                     <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/cashiers/new.html.erb
<h1>Add Cashier</h1>
<%#narrowed the problem for cashiers to this page
I think the parameters are being rejected. looking thorugh this now -Raf

Use comments please Cabanes - Ino <3 %>

<!--Finally working. It was the extra ruby code I didn't completely comment out-->
<%= simple_form_for @cashier do |f| %>

    <%= f.input :email, placeholder: "Cashier email", required: true %>
    <%= f.input :password, placeholder: "Cashier password", required: true %>
    <%= f.input :password_confirmation, placeholder: "Cashier password", required: true %>
    <%= f.input :name, placeholder: "Cashier name", required: true %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to "Go back to Cashiers list", cashiers_path, class: "btn btn-primary" %>
<% end %>

app/views/cashiers/show.html.erb
<h1>Cashier</h1>
 <%= link_to 'Back', :back, class: "btn btn-primary" %><br>
Name: <%= @cashier.name %><br>
Email: <%= @cashier.email %><br>
Orders Processed:

<table class="table table-striped">
    <thead>
        <th>Order ID</th>
        <th>Order Date</th>
        <th>Total Price</th>
        <th colspan="4"></th>
    </thead>
    <tbody>
        <% @cashier.orders.each do |order| %>
            <tr>
                <td class="col-md-4">
                    <%= order.id %>
                </td>
                <td class="col-md-4">
                     <%=  order.created_at %>
                </td>
                <td class="col-md-4">
                    <%= order.total_price %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/orders/_form.html.erb
<%= simple_form_for @order, html: { class: "form-vertical"} do |f| %>
    <% #order_lines %>
    <%= f.simple_fields_for :order_lines do |order_line| %>
        <%= render 'order_line_fields', f: order_line %>
    <% end %>
    <div class='links'>
        <%= link_to_add_association 'Add item', f, :order_lines, class: "btn btn-primary" %>
    </div>
    <br>
    <%= f.input :cash, as: "decimal", placeholder: "Cash", input_html: { min: '0', step: 'any' }, required: true %>
    <%= f.submit 'Save', class: "btn btn-primary" %>
    <%= link_to 'Submit', summary_index_path, class: "btn btn-primary" %>
    <%= link_to "Cancel", orders_path, class: "btn btn-primary" %>
<% end%>

app/views/orders/_order_line_fields.html.erb
<div class='nested-fields'>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Product name</h3>
    </div>
  <div class="panel-body">
    <%= f.collection_select :product_id, Product.where(status: true), :id, :name, required: true, :include_blank => true %>
    <%#= f.association :products, as: :collection_select, label: "Product name", required: true %>
    
    <%= f.input :quantity, as: "integer", placeholder: "Quantity", input_html: { min: '0', step: '1' }, required: true %>
    
    <%= link_to_remove_association "Remove item", f, class: "btn btn-danger"%>
    
    <%= f.hidden_field :order, :value => @order.id %>
    
  </div>
  </div>
</div>

app/views/orders/confirmation.html.erb
<h1>Order Summary</h1>
<%= simple_form_for @order do |f| %>
<table class = "table table-striped">
    <thead>
        <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
        <th>Cash</th>
        </tr>
    </thead>
    <tbody>
        
        <% @orders.each do |order| %>
        <tr>
        <td><%= order.order_lines.name %> </td>
        <td><%= order.order_lines %> </td>
        <% end %>
        <% @orders.each do |order| %>
        <td> <%= order.total_price %></td>
        <td><%= order.cash %></td>
        </tr>
        <% end %>
    </tbody>
    Input payment here:
    <%= f.input:cash, as: "decimal", placeholder: "Payment", input_html: { min: '0', step: 'any' }, required: true %>
    <%= f.submit_tag 'Confirm', class: "btn btn-primary" %>    
</table>
<% end %>

app/views/orders/index.html.erb
<h1>Pending Orders</h1>

<%= link_to "Place New Order", new_order_path, :class => 'btn btn-primary' %>
<table class = "table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Cashier</th>
            <th>Total</th>
            <th>Cash</th>
            <th>Order</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @orders.each do |order| %>
            <tr>
            <td>
                <%= order.id %>
            </td>
            <td>
                Placeholder
            </td>
            <td>
                <%= order.total_price %>
            </td>
            <td>
                <%= order.cash %>
            </td>
            <td>
               <%= link_to 'View', summary_index_path, class: "btn btn-primary" %>
            </td>
            <td>
                <%= link_to "Delete", order, method: :delete, class: "btn btn-danger" %>
            </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/orders/new.html.erb
<h1> Place A New Order </h1>

<%= render 'form' %>

app/views/orders/show.html.erb
<h1>Order Summary</h1>
 <%= link_to 'Back', :back, class: "btn btn-primary" %><br>
<b>Order ID:</b> <%= @order.id %><br>

<table class="table table-striped">
    <thead>
        <th>Product Name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th colspan="4"></th>
    </thead>
    <tbody>
        <% @order.order_line_fields.each do |order| %>
            <tr>
                <td class="col-md-4">
                    <%= order.name %>
                </td>
                <td class="col-md-4">
                     <%=  order.quantity %>
                </td>
                <td class="col-md-4">
                    <%= order.total_price %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= simple_form_for @product do |f| %>
    <%= f.input :name, placeholder: "Product name", required: true %>
    <%= f.input :price, as: "decimal", placeholder: "Price", input_html: { min: '0', step: 'any' }, required: true %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "Create New Product", new_product_path, :class => 'btn btn-primary' %>

<table class="table table-striped" style="background-color: Khaki ">
    <thead>
        <th>Name</th>
        <th>Price</th>
        <th>Status</th>
        <th colspan="3"></th>
       
    </thead>
    <tbody>
        <% @products.each do |product| %>
            <tr>
                <td class="col-md-6">
                    <%= product.name %>
                </td>
                <td class="col-md-1">
                    <%= product.price %>
                </td>
                <td class="col-md-1">
                    <% if product.status == true %>
                    <p class= "label label-success">Active</p>
                    <% else %>
                    <p class= "label label-danger">Inactive </p>
                    <% end %>
                </td>
                <td>
                    <%= link_to "Edit", edit_product_path(product), class: "btn btn-primary" %>
                </td>
                <td>
                    <%= link_to "View", product, class: "btn btn-warning" %>
                </td>
                <td>
                     <% if product.status == true %>
                    <%= link_to "Deactivate", product, method: :delete, class: "btn btn-danger" %>
                    <% else %>
                     <%= link_to "Activate", product, method: :delete, class: "btn btn-success" %>
                     <% end %>
                       
                    
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= simple_form_for @product do |f| %>
    <%= f.input :name, placeholder: "Product name", required: true %>
    <%= f.input :price, as: "decimal", placeholder: "Price", input_html: { min: '0', step: 'any' }, required: true %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', :back, class: "btn btn-primary" %>
<% end %>

app/views/products/show.html.erb
<h1>Product Information</h1>

<b>Name:</b> <%= @product.name %><br>
<b>Price:</b> <%= @product.price %><br>
<b>Product Status: 
<% if @product.status == true %>
    Active
    <% else %>
    Inactive
<% end %>
<br>
 <%= link_to "Go back to Product list", products_path, class: "btn btn-primary" %>