config/routes.rb
Rails.application.routes.draw do
  get 'summary/index'

  get 'order_lines/index'

  get 'order_lines/new'

  devise_scope :admin do
    get 'admins/sign_in', to: 'publics#index' #failed sign ins will redirect to main page
    authenticated :admin do
      resources :cashiers
      resources :products
      resources :report
      root 'products#index', as: :authenticated_admin_root
      get 'report/index'
    end
  end
  
  devise_scope :cashier do
    get 'cashiers/sign_in', to: 'publics#index' #failed sign ins will redirect to main page
    # added below
    authenticated :cashier do
      resources :products
      resources :orders
      resources :order_lines
      root 'orders#index'
    end
  end

  devise_for :cashiers
  devise_for :admins
  root 'publics#index'
  get 'publics/catalogue'
  get 'order_lines/index'
  get 'order_lines/new'
  get 'orders/new'
  get 'orders/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :cashiers
end

# removed :registerable

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :admin
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_lines, inverse_of: 'order'
  accepts_nested_attributes_for :order_lines, reject_if: :all_blank, allow_destroy: true
  belongs_to :cashier
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  has_and_belongs_to_many :products
  belongs_to :order
  
end

app/models/product.rb
class Product  < ActiveRecord::Base
    has_many :order_lines
    has_many :orders, :through => :order_lines
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  before_action :set_cashier, only: [:edit, :show, :update, :destroy
  ]
  
  def index
    @cashiers = Cashier.all
  end

  def new
    @cashier = current_admin.cashiers.new
  end
  
  def create
   @cashier = current_admin.cashiers.new(cashier_params)
   
    @cashier.status = true
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully added."
    else
      render :new
     
    end
  end
  
  def edit
  end

  def show
  end
 
  def destroy
    @cashier = Cashier.find(params[:id])
    if @cashier.status == true
      @cashier.status = false
    else
      @cashier.status = true
    end
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    end
  end
  
  #version below turns change status to "delete cashier"
  # def destroy
  #   @cashier = Cashier.find(params[:id])
  #   @cashier.destroy
    
  #   redirect_to cashiers_path
  # end
    
  def update
    @cashier = Cashier.find(params[:id])
    @cashier.destroy
    @cashier = current_admin.cashiers.new(cashier_params)
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    else
      render :edit
    end
  end
  
  private
    def set_cashier
      @cashier = Cashier.find_by(id: params[:id])
      redirect_to cashiers_path, notice: "Cashier not found." if @cashier.nil?
    end
    
    def cashier_params
       params.require(:cashier).permit(:email, :password, :password_confirmation, :name) #-> Tried this
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:edit, :show, :update, :destroy]
  
  def index
      @orders = Order.all
      @order_lines = OrderLine.all
  end
  
  def new
      @order = Order.new
  end
  
  def create
      @order = Order.new(order_params)
      @order.cashier = current_cashier
      @order.total_price = 0
      
      if @order.save
        
        redirect_to orders_path, notice: "Order successfully placed."
      else
        render :new
      end
  end
  
  def destroy
    # what?
      @order = Order.find(params[:id])
      @order.destroy
    
      redirect_to orders_path
  end
  
  def back
      redirect_to :back
  end
  
  private
    def set_order
        @order = Order.find_by(id: params[:id])
        redirect_to orders_path, notice: "Order not found." if @order.nil?
    end
    
    def order_params
      params.require(:order).permit(:cashier_id, :total_cash, :cash, order_line_attributes: [:id, :product_id, :order_id, :quantity, :price, :_destroy])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :show, :update, :destroy]
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    @product.status = "Active"
    
    if @product.save
      redirect_to products_path, notice: "Product successfully added."
    else
      render :new
    end
  end
  
  def edit
    
  end

  def show
  end
  
  def update
    @product.update(product_params)
    if @product.save
      redirect_to products_path, notice: "Product successfully updated."
    else
      render :edit
    end
  end
  
  def destroy
    if @product.status == true
      @product.status = false
    else
      @product.status = true
    end
    
    if @product.save
      redirect_to products_path, notice: "Product successfully updated."
    end
  end
  
  private
    def set_product
      @product = Product.find_by(id: params[:id])
      redirect_to products_path, notice: "Product not found." if @product.nil?
    end
    
    def product_params
      params.require(:product).permit!
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  end
  
  def catalogue
    @products = Product.all
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  
  def index
     @products = Product.all
     
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def index
    @order_line = OrderLine.all
    @orders = Order.all
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>POS Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">POS Application</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if admin_signed_in? %>
              <li>
                <%= link_to "Products", products_path %>
              </li>
              <li>
                <%= link_to "Cashiers", cashiers_path %>
              </li>
              <li>
                <%= link_to "Report", report_index_path %>
              </li>
            <% end %>
            <% if cashier_signed_in? %>
              <li>
                <%= link_to "Orders", orders_path %>
              </li>
            <% end %>
          </ul>
          
          <p class="navbar-text pull-right">
          <% if admin_signed_in? %>
             Admin logged in as <strong><%= current_admin.email %></strong> |
            <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
          <% if cashier_signed_in? %>
             Cashier logged in as <strong><%= current_cashier.email %></strong> |
            <%= link_to "Logout", destroy_cashier_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
          </p>
        </div>
      </div>
    </nav>
    
    
    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </div>
    
  </body>
</html>